services:
  - type: static
    name: sibomsacks-frontend
    env: node
    buildCommand: npm run build
    staticPublishPath: dist
    branch: main
    repo: https://github.com/mtcarrixo/Sibomsacks
    routes:
      - type: rewrite
        source: /.*     # Todas las rutas
        destination: /index.html
